name = "AnalyticComb"
uuid = "8a73a7cf-268c-4a55-9a00-18d79986516d"
authors = ["fargolo <felipe.c.argolo@protonmail.com> and contributors"]
version = "1.0.3"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"

[compat]
julia = "1"
Reexport = "1.2" 
SymPy = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
